name: Run third action
description: Run the third action in this repo

runs:
  using: composite
  steps: 
    - name: Run script
      id: hello-world
      run: ./action-3/hello-world.sh
      shell: bash