name: Run third action
description: Run the third action in this repo

inputs:
  platform:
    description: 'Platform to check for updates'
    required: true
    default: 'macos'
  var-2:
    description: 'Input 2'
    required: false
    default: 'Hello'
  var-3:
    description: 'Input 3'
    required: false
    default: 'World'

runs:
  using: composite
  steps: 
    - name: check out code
      uses: actions/checkout@v4
      with: 
        repository: skeenan07/github-actions-test-callable
        ref: main

    - name: Run script
      id: hello-world
      run: ./action-3/hello-world.sh "${{ inputs.platform }}" "${{ inputs.var-2 }}" "${{ inputs.var-3 }}"
      shell: bash