name: Check for macOS Update
description: Check for macOS update released in the last week

outputs:
  updates-available: 
    description: 'iOS update available'
    value: ${{ steps.check-ios-update.outputs.updates-available }}

runs:
  using: composite
  steps: 
    - name: check out code
      uses: actions/checkout@v4

    - name: List files
      run: ls -la
      shell: bash

    - name: Run script
      id: check-macos-update
      run: ./check-for-macOS-update.sh
      shell: bash