name: Root Action

on:
  workflow_call:
    inputs:
      var-1:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      var-1:
        description: 'Group type: COMPUTER or DEVICE'
        required: true
        type: choice
        options:
          - COMPUTER
          - DEVICE
        default: COMPUTER

jobs:

  run-action-1:
    if: ${{ github.event.inputs.var-1 == 'COMPUTER' }}
    uses: ./.github/workflows/check-for-macOS-updates.yml
    with:
      var-1: ${{ github.event.inputs.var-1 }}

  run-action-2:
    needs: run-action-1
    if: ${{ github.event.inputs.var-1 == 'DEVICE' }}
    uses: ./.github/workflows/check-for-iOS-updates.yml
    with:
      var-1: ${{ github.event.inputs.var-1 }}

  updates-available:
    runs-on: ubuntu-latest
    needs: [run-action-1, run-action-2]
    if: ${{ needs.run-action-1.outputs.updates_available == 'true' }} || ${{ needs.run-action-2.outputs.updates_available == 'true' }}
    steps:
      - run: echo "Updates are available"

  updates-not-available:
    runs-on: ubuntu-latest
    needs: [run-action-1, run-action-2, updates-available]
    if: ${{ needs.run-action-1.outputs.updates_available == 'false' }} || ${{ needs.run-action-2.outputs.updates_available == 'false' }}
    steps:
      - run: echo "No updates are available"

